name: Deploy Academic QA API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Copy project files to server via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "/home/${{ secrets.SERVER_USER }}/academic-qa"

    - name: SSH and deploy with Docker Compose
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/${{ secrets.SERVER_USER }}/academic-qa
          echo "${{ secrets.ENV_CONTENT }}" > .env
          docker-compose down
          docker-compose up -d --build
